# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 21:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160528_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 28, 21, 56, 37, 544978, tzinfo=utc)),
        ),
    ]
